#class register:
print('******************Welcome to Registration Section**********************\n')
print('Kindly Enter the following Details to get registered with us\n')
self.name = raw_input('Please enter your name: ')
print('\n')
self.age = raw_input('Enter your age: ')
print('\n')
self.model = raw_input('Enter your Bike model: ')
print('\n')
self.dl = raw_input('Enter your Driving license: ')
print('\n')
self.emerge_no = raw_input('Enter the Emergency number to be contacted: ')
print('\n')
self.Insure_no = raw_input('Enter the insurance no: ')
print('\n')
self.Insure_date = raw_input('Enter the Bike Insurance expiry date: ')
